<?php $f = $t->_('register_form') ?>
<?= $f->_start() ?>
<?= $f->_errors() ?>
<p><?= $f->_input('username')->label('Pseudo')
    ->alphanum()->required()
    ->minlength(4)->maxlength(32)->html() ?></p>
<p><?= $f->_input('password')->label('Mot de passe')
    ->password(true)->required()
    ->minlength(8)->html() ?></p>
<p><?= $f->_input('password-bis')->label('Confirmation')
    ->password(true)->required()
    ->minlength(8)->html() ?></p>
<p><?= $f->_input('mail')->label('Mail')
    ->email()->required()->html() ?></p>
<p><?= $f->_input('discord')->label('ID Discord')
    ->regex('\d*')->required()->minlength(8)->maxlength(20)->html() ?></p>
<p><?= $f->_submit('S\'inscrire') ?></p>
<?= $f->_end() ?>