<?php $custom = $t->_('custom');
$action = $custom->_id->_id;
$t->_layout('Main')
    ->set('Title', 'Action - Jet personalisé')
    ->_section('body') ?>
<h2>Jet personalisé de <?= $t->_e($action->_character->getFullName()) ?></h2>
<section>
    <?php if(!$action->valid): ?>
    <p class="errors">Attention: ce jet n'est pas encore validé</p>
    <?php endif ?>
    <p>Personnage: <a href="/<?= $t->_('router')->get('character')->getUrl(['id' => $action->character]) ?>"><?= $t->_e($action->_character->getFullName()) ?></a></p>
    <p>Lieu: <a href="/<?= $t->_('router')->get('world place')->getUrl(['id' => $action->place]) ?>"><?= $t->_e($action->_place->getFullName()) ?></a></p>
    <p>Date: <?= $t->_e($action->date) ?></p>
    <p>Utilisateur: <a href="/<?= $t->_('router')->get('user')->getUrl(['id' => $action->user]) ?>"><?= $t->_e($action->_user->name) ?></a></p>
    <p>Type de dé(s): <?= $t->_e($custom->roll) ?></p>
    <p>Valeurs: <?= $t->_e(implode(' ', $custom->getDiceValues())) ?></p>
    <div>
        <h3>Description</h3>
        <p><?= $t->_e($custom->_id->description) ?></p>
    </div>
</section>
<?php $t->_endsection() ?>