<?php $t->_layout('Main')
    ->set('Title', 'Météo')
    ->set('Description', "La météo des régions en temps réel")
    ->_section('body') ?>
<h2>Météo des régions</h2>
<section>
    <?php if($t->_x('regions')): ?>
    <?php foreach ($t->_('regions') as $region): ?>
    <article style="display: inline-block; margin: 10px; padding: 10px; border: 5px <?= [1 => 'yellow', 'lightgrey', 'blue', 'grey'][$region->weather] ?> solid">
        <h3><?= $t->_e($region->name) ?></h3>
        <p style="color: <?= [1 => 'yellow', 'lightgrey', 'blue', 'grey'][$region->weather] ?>"><?= $t->_e($region->_weather->name) ?></p>
    </article>
    <?php endforeach ?>
    <?php else: ?>
    <p>Vous n'avez aucune région</p>
    <?php endif ?>
</section>
<?php $t->_endsection() ?>