<?php $t->_layout('Main')
    ->set('Title', 'Météo')
    ->set('Description', "La météo des régions en temps réel")
    ->_section('body') ?>
<h2>Météo des égions</h2>
<section>
    <?php if($t->_x('regions')): ?>
    <?php foreach ($t->_('regions') as $region): ?>
    <article style="display: inline-block; padding: 10px; background-color: <?= [1 => 'yellow', 'light-grey', 'blue', 'grey'][$region->_weather->id] ?>; border: 5px var(--main-bg-hover-color) solid">
        <h3><?= $t->_e($region->name) ?></h3>
        <p><?= $t->_e($region->_weather->name) ?></p>
    <article>
    <?php endforeach ?>
    <?php else: ?>
    <p>Vous n'avez aucune région</p>
    <?php endif ?>
</section>
<?php $t->_endsection() ?>