<?php $f = $t->_('success_form') ?>
<?= $f->_start() ?>
<?= $f->_errors() ?>
<p><?= $f->_select('element')->label('Element')->options($t->_('elements'))->required()->html() ?></p>
<?php if(!empty($t->_('weapons'))): ?>
    <p><?= $f->_select('weapon')->label('Arme')->options($t->_('weapons'))->html() ?></p>
<?php endif ?>
<p><?= $f->_input('bonus')->label('Bonus')->number()->min(0)->max(100)->value(0)->required()->html() ?></p>
<p><?= $f->_input('count')->label('Nombre de lancés')->number()->min(1)->max(20)->value(1)->required()->html() ?></p>
<p><?= $f->_input('considered')->label('Pris en compte')->checkbox()->html() ?></p>
<p><?= $f->_textarea('description')->label('Description')->required()->html() ?></p>
<p><?= $f->_submit('Valider') ?></p>
<?= $f->_end() ?>