<?php
$user = $t->_('user');
$t->_layout('Main')
    ->set('Title', 'Utilisateur - '.$user->name)
    ->set('Description', "Fiche du compte")
    ->_section('body') ?>
<h2><?= $t->_e($user->name) ?></h2>
<section>
    <?php if(!$user->_role->canConnect): ?>
    <p class="errors">Attention: ce compte n'est pas encore validé</p>
    <?php endif ?>
    <p>Nom: <?= $t->_e($user->name) ?></p>
    <p>Discord: <?= $t->_e($user->discord) ?></p>
    <p>Role: <?= $t->_e($user->_role->name) ?></p>
    <div>
        <h3>Personnages</h3>
        <?php if(empty($user->_characters)): ?>
        <p>Aucun personnage</p>
        <?php else: ?>
        <ul>
            <?php foreach($user->_characters as $character): ?>
            <li><a href="/<?= $t->_('router')->get('character')->getUrl(['id' => $character->id]) ?>"><?= $t->_e($character->getFullName()) ?></a></li>
            <?php endforeach ?>
        </ul>
        <?php endif ?>
        <?php if(!empty($user->_rights)): ?>
        <table>
            <tr><th>Nom</th><th>Jouer</th><th>Modifier</th><th>Gerer</th></tr>
            <?php foreach($user->_rights as $right): ?>
            <tr>
                <td><a href="/<?= $t->_('router')->get('character')->getUrl(['id' => $right->character]) ?>"><?= $t->_e($right->_character->getFullName()) ?></a></td>
                <td><?= $right->canPlay ? 'X' : '' ?></td>
                <td><?= $right->canEdit ? 'X' : '' ?></td>
                <td><?= $right->canManage ? 'X' : '' ?></td>
            </tr>
            <?php endforeach ?>
        </table>
        <?php endif ?>
    </div>
</section>
<?php $t->_endsection() ?>