<?php $t->_layout('Main')
    ->set('Title', 'Inscription réussie')
    ->set('Description', "Bravo pour votre inscription")
    ->_section('body') ?>
<h2>Inscription réussie</h2>
<section>
    <h3>Bravo pour votre inscription</h3>
    <p>Votre compte doit maintenant être activé par un administrateur</p>
    <p>Vous pourrez ensuite pour connecter</p>
    <p><a href="<?= $t->_('login_url') ?>"><button>Se connecter</button></a></p>
</section>
<?php $t->_endsection() ?>