<?php $t->_layout('Main')
    ->set('Title', 'Validation des personnages')
    ->_section('body') ?>
<h2>Personnages</h2>
<section>
    <?php if($t->_x('characters')): ?>
    <table>
        <tr><th>Nom</th><th>Createur</th></tr>
        <?php foreach ($t->_('characters') as $character): ?>
        <tr>
            <td><a href="/<?= $t->_('router')->get('character')->getUrl(['id' => $character->id]) ?>"><?= $t->_e($character->getFullName()) ?></a></td>
            <td><?= $t->_e($character->_owner->name) ?></td>
            <td><form method="post">
                <input type="hidden" name="character_id" value="<?= $t->_e($character->id) ?>">
                <input type="submit" value="Valider">
            </form></td>
        </tr>
        <?php endforeach ?>
    </table>
    <?php else: ?>
    <p>Aucun personnage en attente</p>
    <?php endif ?>
</section>
<?php $t->_endsection() ?>