<?php $t->_layout('Main')
    ->set('Title', 'Création réussie')
    ->set('Description', "Bravo pour la création de votre personnage")
    ->_section('body') ?>
<h2>Création réussie</h2>
<section>
    <h3>Bravo pour la création de votre personnage</h3>
    <p>Votre personnage doit maintenant être validé par un administrateur</p>
    <p>Il vous contactera ensuite pour définir ses caractéristiques</p>
</section>
<?php $t->_endsection() ?>