<?php
$character = $t->_('character');
$t->_layout('Main')
    ->set('Title', 'Personnage - '.$character->getFullName())
    ->set('Description', "Fiche privé du personnage")
    ->_section('body') ?>
<h2><?= $t->_e($character->getFullName()) ?></h2>
<section>
    <?php if(!$character->valid): ?>
    <p class="errors">Attention: ce personnage n'est pas encore validé</p>
    <?php endif ?>
    <p>Nom: <?= $t->_e($character->surname) ?></p>
    <p>Prenom: <?= $t->_e($character->firstname) ?></p>
    <?php if($character->nickname != null): ?>
    <p>Surnom: <?= $t->_e($character->nickname) ?></p>
    <?php endif ?>
    <p>Race: <?= $t->_e($character->race) ?></p>
    <p>Naissance: <?= (new \DateTime($character->birthday))->format('d m Y') ?></p>
    <p>Taille: <?= $t->_e($character->size) ?>cm</p>
    <p>Poids: <?= $t->_e($character->weight) ?>kg</p>
    <p>Alignement: <?= $t->_e($character->_alignment->name) ?></p>
    <article>
        <h3>Personalité</h3>
        <p><?= $t->_e($character->personality) ?></p>
    </article>
    <article>
        <h3>Description</h3>
        <p><?= $t->_e($character->description) ?></p>
    </article>
    <article>
        <h3>Histoire</h3>
        <p><?= $t->_e($character->history) ?></p>
    </article>
    <p>Lieu actuel: <?= $t->_e($character->_place->name) ?></p>
    <p>Createur: <?= $t->_e($character->_owner->name) ?></p>
</section>
<?php $t->_endsection() ?>