<?php $t->_layout('Main')
    ->set('Title', 'Personnages')
    ->set('Description', "Vos personnages")
    ->_section('body') ?>
<h2>Personnages</h2>
<section>
    <?php if($t->_x('characters')): ?>
    <table>
        <tr><th>Nom</th><th>Prénom</th></tr>
        <?php foreach ($t->_('characters') as $character): ?>
        <tr>
            <td><?= $t->_e($character->surname) ?></td>
            <td><?= $t->_e($character->firstname) ?></td>
            <td><a href="/<?= $t->_('router')->get('character')->getUrl(['id' => $character->id]) ?>"><button>Voir</button></a></td>
            <td><?php if ($character->id != $t->_('current_character')): ?><form method="post">
                <input type="hidden" name="character_id" value="<?= $t->_e($character->id) ?>">
                <input type="submit" value="Séléctionner">
            </form><?php else: ?><a href="/<?= $t->_('router')->get('actions')->getUrl(['id' => $character->id]) ?>"><button>Jouer</button></a><?php endif ?></td>
        </tr>
        <?php endforeach ?>
    </table>
    <?php else: ?>
    <p>Vous n'avez aucun personnage</p>
    <p><a href="/<?= $t->_('router')->get('character create')->getUrl() ?>">En creer un</a></p>
    <?php endif ?>
</section>
<?php $t->_endsection() ?>