<?php $t->_layout('Main')
    ->set('Title', 'Raith')
    ->set('Description', 'Organize your text roleplay easily')
    ->_section('body') ?>
<section>
    <article class="index-menu-container">
        <div id="top-left" class="menu">
            <div></div>
            <p class="menu-title">Histoire</p>
        </div>
        <div id="top-center" class="menu">
            <div></div>
            <p class="menu-title">Races</p>
        </div>
        <div id="top-right" class="menu">
            <div></div>
            <p class="menu-title">Monde</p>
        </div>
        <div id="bot-left" class="menu">
            <div></div>
            <p class="menu-title">Gameplay</p>
        </div>
        <div id="bot-center" class="menu">
            <div></div>
            <p class="menu-title">Règles</p>
        </div>
        <div id="bot-right" class="menu">
            <div></div>
            <p class="menu-title">Jouer</p>
        </div>
    </article>
</section>
<section>
    <article id="resume">
        <h1 id="nani">Qu'est ce que Raith ?</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non sem venenatis, rutrum sem et, rutrum nunc. Sed placerat nibh id metus ornare, sit amet viverra tellus aliquet. Vivamus cursus vehicula lacus, id laoreet sapien faucibus eu. Maecenas quam velit, laoreet at est vel, feugiat convallis eros. Maecenas dictum ornare ligula at pharetra. Maecenas est arcu, varius sit amet pharetra sit amet, ullamcorper a mauris. Aenean at nisi condimentum, auctor ante at, suscipit odio. In a neque et turpis aliquam viverra. Phasellus in elit fermentum, egestas ligula vitae, auctor eros.        
        <br/>
            Nunc eu erat eget mauris consectetur tincidunt eget vel sem. Donec malesuada neque et risus feugiat bibendum. Sed commodo, ante in rutrum venenatis, nulla ipsum sagittis nibh, eu feugiat ipsum dolor sit amet tortor. Quisque lacinia egestas ante pulvinar ultricies. In in dolor tristique, tempus dui in, consequat augue. Fusce eu ante sollicitudin metus congue sodales. Mauris hendrerit, eros vel condimentum venenatis, orci mi dignissim dolor, id dictum turpis velit quis risus. Mauris laoreet blandit quam nec fermentum. Suspendisse pellentesque nunc sed risus condimentum vulputate. Cras malesuada ligula in sapien luctus lobortis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer eu suscipit sem, vitae fringilla nibh. Phasellus porta tincidunt ante, non dapibus massa ullamcorper id. Pellentesque ex tortor, maximus ut volutpat ac, fermentum sed nisi. Integer vitae congue quam.
        </p>
    </article>
</section>
<?php $t->_endsection() ?>