<!DOCTYPE>
<html lang='fr' prefix="og: http://ogp.me/ns#">
	<head>
		<meta charset="utf-8" />
		<!--[if lt IE 9]>
		<script src='http://html5shiv.googlecode.com/svn/trunk/html5.js'></script>
		<![endif]-->
        <!--<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>-->
		<meta property="og:locale" content="fr_FR" />
		<meta property="og:type" content="website" />
		<meta property="og:url" content="<?php echo "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"; ?>" />
		<meta property="og:site_name" content="Raith" />
		<meta name='viewport' content='width=device-width'/>
        <title><?= $t->_('Title') ?></title>
        <?= $t->_p('Description', '<meta name="description" content="{?}"/>') ?>
        <link href="/css/style.css" rel="stylesheet"/>
        <script src="/js/jquery.js"></script>
		<?= $t->_content('head') ?>
    </head>
    <body>
        <header>
            <h1><a href='/'>Raith</a></h1>
        </header>
        <nav>
            <ul>
                <li class="left"><a href="/#nani">Qu'est ce que Raith ?</a></li>
                <li class="secleft"><a href="">Contacts</a></li>
                <li class="connect"><a href="/login">Se connecter</a></li>
            </ul>
        </nav>
        <div class="body">
             <?= $t->_content('body') ?>
        </div>
        <footer>
		
        </footer>
    </body>
</html>
