<!DOCTYPE>
<html lang='fr' prefix="og: http://ogp.me/ns#">
	<head>
		<meta charset="utf-8" />
		<!--[if lt IE 9]>
		<script src='http://html5shiv.googlecode.com/svn/trunk/html5.js'></script>
		<![endif]-->
		<meta property="og:locale" content="fr_FR" />
		<meta property="og:type" content="website" />
		<meta property="og:url" content="<?php echo "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"; ?>" />
		<meta property="og:site_name" content="Raith" />
		<meta name='viewport' content='width=device-width'/>
        <title><?= $t->_('Title') ?></title>
        <?= $t->_p('Description', '<meta name="description" content="{?}"/>') ?>
        <link href="/css/style.css" rel="stylesheet"/>
		<?= $t->_content('head') ?>
    </head>
    <body>
        <header>
            <h1><a href='/'>
				Raith
			</a></h1>
        </header>
        <nav>

        </nav>
        <section>
             <?= $t->_content('body') ?>
        </section>
        <footer>
		
        </footer>
    </body>
</html>
