<?php $t->_layout('Main')
    ->set('Title', 'Administration')
    ->_section('body') ?>
<h2>Administration</h2>
<section>
    <p>Un outil pour gerer le rp</p>
    <ul>
        <li><a href="/<?= $t->_('router')->get('admin validate users')->getUrl() ?>">Utilisateurs</a></li>
        <li><a href="/<?= $t->_('router')->get('admin validate characters')->getUrl() ?>">Personnages</a></li>
        <li><a href="/<?= $t->_('router')->get('admin validate actions')->getUrl() ?>">Actions</a></li>
    </ul>
</section>
<?php $t->_endsection() ?>