<?php $f = $t->_('character_form') ?>
<?= $f->_start() ?>
<?= $f->_errors() ?>
<p><?= $f->_input('nom')->label('Nom : ') //TODO: add minlength et maxlength
    ->alpha()->required()
    ->html() ?></p>

<p><?= $f->_input('prenom')->label('Prénom : ') //TODO: add minlength et maxlength
    ->alpha()->required()
    ->html() ?></p>

<p><?= $f->_input('surnom')->label('Surnom : ')
    ->alpha()
    ->html() ?></p>

<p><?= $f->_select('race')->label('Race : ')
    ->options($t->_('character_races'))
    ->other($f->_input('Autre', false)->alpha()->required(), 'Autre')
    ->required()->html() ?></p>

<p><?= $f->_input('dateNaissance')->label('Date de naissance : ') //TODO: ajouter une note
    ->date()->required()
    ->max('1240-01-01')
    ->html() ?></p>

<p><?= $f->_input('taille')->label('Taille : ') //TODO: add max (m ou cm)
    ->number()->required()
    ->min(0)->html() ?></p>

<p><?= $f->_input('poids')->label('Poids : ') //TODO: add max (kg?)
    ->number()->required()
    ->min(0)->html() ?></p>

<p><?= $f->_select('alignement')->label('Alignement : ')
    ->options($t->_('character_alignments'))
    ->required()->html() ?></p>

<p><?= $f->_textarea('personnalite')->label('Personnalité : ')
    ->required()->html() ?></p>

<p><?= $f->_textarea('descPhysique')->label('Description physique : ')
    ->required()->html() ?></p>

<p><?= $f->_textarea('histoire')->id('histoire')->label('Histoire : ')
    ->required()->html() ?></p>

<div id='maitrises'>
    <h3>Maitrises : </h3>
    <div id='maitrises-armes'>
        <h4>Armes : </h4>
        <p><?= $f->_select('', false)->id('select-maitrises-arme')
            ->options($t->_('weapon_types'))->html('class="hidden"'); ?></p>

        <?php foreach ($t->_('weapon_types') as $arme): ?>
        <p><?= $f->_input($arme['value'])->label($arme['text'].' :')
            ->number()->min(0)->max(30)->html("class='champ-maitrises-arme'") ?></p>
        <?php endforeach ?>
    </div>
    <div id='maitrises-metiers'>
        <h4>Métiers : </h4>
        <p><?= $f->_select('', false)->id('select-maitrises-metier')
            ->options($t->_('jobs'))->html('class="hidden"'); ?></p>

        <?php foreach ($t->_('jobs') as $metier): ?>
        <p><?= $f->_input($metier['value'])->label($metier['text'].' :')
            ->number()->min(0)->max(30)->html("class='champ-maitrises-metier'") ?></p>
        <?php endforeach ?>
    </div>
</div>
<p><?= $f->_submit('Enregistrer') ?></p>
<?= $f->_end() ?>