<?php $t->_layout('Main')
    ->set('Title', 'Actions')
    ->_section('body') ?>
<h2>Actions pour <?= $t->_e($t->_('character')->getFullName()) ?></h2>
<section>
    <ul>
        <!--<li><a href="/<?= $t->_('router')->get('action message')->getUrl() ?>">Parler</a></li>-->
        <li><a href="/<?= $t->_('router')->get('action roll success')->getUrl() ?>">Jet de reussite</a></li>
        <li><a href="/<?= $t->_('router')->get('action roll damage')->getUrl() ?>">Jet de degat</a></li>
        <li><a href="/<?= $t->_('router')->get('action roll custom')->getUrl() ?>">Jet personnalisé</a></li>
    </ul>
</section>
<?php $t->_endsection() ?>